# YOLOv5 ğŸš€ by Ultralytics, AGPL-3.0 license
# COCO128 dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: python train.py --data coco128.yaml
# parent
# â”œâ”€â”€ yolov5
# â””â”€â”€ datasets
#     â””â”€â”€ coco128  â† downloads here (7 MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path:  ../datasets  # dataset root dir
train:  /home/pguedes/YOLOv8/Darwin_dados/datasets/darwin_v6_rotated/images/train  # train images (relative to 'path') 128 images
val:    /home/pguedes/YOLOv8/Darwin_dados/datasets/darwin_v6_rotated/images/val  # val images (relative to 'path') 128 images
test:   /home/pguedes/YOLOv8/Darwin_dados/datasets/darwin_v6_rotated/images/test
task: segment

# Classes
names:
  0: Equipamentos
  1: Escada
  2: Estruturas
  3: Guarda Corpo
  4: Piso
  5: Suportes
  6: TVF
  7: Teto
